version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: python manage.py test
      - run:
          name: Linting
          command: flake8

  create-and-push-docker-image:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create docker image and push it to Docker Hub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker build -t franqui/oc-lettings-fq:$CIRCLE_SHA1 .
            docker push franqui/oc-lettings-fq:$CIRCLE_SHA1

  publish-image-on-heroku:
    machine: true
    steps:
      - checkout
      - run :
          name: build, push, deploy image to heroku
          command : |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push franqui/oc-lettings-fq:$CIRCLE_SHA1 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release franqui/oc-lettings-fq:$CIRCLE_SHA1 web

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - create-and-push-docker-image:
          requires:
            - build-and-test
      - publish-image-on-heroku:
          requires:
            - create-and-push-docker-image
          filters:
            branches:
              only:
                - master