version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - setup_remote_docker
      - run:
          name: Test run
          command: pytest -s --no-migration
    docker:
      - image: cimg/python:3.10.2
    environment:
      IMAGE_NAME: franqui/oc-lettings-fq